spring:
  application:
    name: contract-command
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_cqrses_service
    username: postgres
    password: Phieu2106
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8301