spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/user_cqrses_service
    username: postgres
    password: Phieu2106
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9999
