spring:
  application:
    name: customer-flow
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_cqrses_service
    username: postgres
    password: Phieu2106
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8202